platform:
- x64

environment:
  nodejs_version: "9"

cache:
- 'node_modules'
- '%USERPROFILE%\.electron'

# Install scripts. (runs after repo cloning)
install:
  # install node
  - ps: Install-Product node $env:nodejs_version
  # install node modules
  - npm install
  - npm prune
  # build electron package
  - npm run make -- --platform=win32,linux --arch=x64

test_script:
  - node --version
  - npm --version

artifacts:
  - path: out\make\*win32*
    name: Windows
  - path: out\make\*linux*
    name: Linux
  - path: out\make\*darwin*
    name: MacOS

# Don't actually build.
build: off