platform:
- x64

environment:
  nodejs_version: "9"

cache:
- 'node_modules'
- '%USERPROFILE%\.electron'

# Install scripts. (runs after repo cloning)
install:
  # install node
  - ps: Install-Product node $env:nodejs_version
  # install node modules
  - npm install
  - npm prune
  # build electron package
  - npm run package -- --platform=win32,linux --arch=x64

test_script:
  - node --version
  - npm --version

artifacts:
  - path: out\retropie-arcade-manager-win32-x64
    name: Retropie-Arcade-Manager-Windows-x64
  - path: out\retropie-arcade-manager-linux-x64
    name: Retropie-Arcade-Manager-Linux-x64

# Don't actually build.
build: off