language: node_js
node_js:
- '9'
os:
- osx
dist: trusty
osx_image: xcode9.3
sudo: required
cache:
  directories:
  - node_modules
env:
  matrix:
  - NODE_INSTALLER=npm
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+/
install:
- npm install
- npm update
- npm prune
script:
- npm run package -- --platform=darwin --arch=x64