platform:
- x64

environment:
  nodejs_version: "9"

cache:
- 'node_modules'
- '%USERPROFILE%\.electron'

# Install scripts. (runs after repo cloning)
install:
  # install node
  - ps: Install-Product node $env:nodejs_version
  # build number
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Update-AppveyorBuild -Version "$($env:package_version)-$env:APPVEYOR_BUILD_NUMBER"
  # install node modules
  - npm install
  - npm prune
  # build electron package
  - npm run dist -- --win --linux --x64

test_script:
  - node --version
  - npm --version

# artifacts:
#   - path: dist\ArcadeManager Setup*.exe
#     name: Arcade Manager Windows (Setup)
#   - path: dist\ArcadeManager-*-win.zip
#     name: Arcade Manager Windows (Standalone)
#   - path: dist\arcade-manager*.snap
#     name: Arcade Manager Linux (Snap)
#   - path: dist\arcade-manager*.AppImage
#     name: Arcade Manager Linux (AppImage)

# Don't actually build.
build: off

# deploy:
# - provider: BinTray
#   username: cosmo0
#   api_key:
#     secure: NWundKYe7riNRrADb64QuUkdctcNJIFT3iVjTu1Yuh/pdPpmaIi8BO35II0ECo00
#   subject: cosmo0
#   repo: arcade-manager
#   package: arcade-manager
#   publish: true
#   override: true
#   explode: false